### PR TITLE
fix: xmlToJson - honor maxOccurs > 1 through `descriptor.isMany`

### LINKED ISSUE #268: Proposal: always return an array for response element where maxOccurs > 1
Currently, strong-soap inherits node-soap's behaviour of returning the following for a given element defined as:
```xml
<xs:sequence>
  <xs:element maxOccurs="(greater than 1)" />
</xs:sequence>
```
this behaviour returns such an element as an object if it occurs once, or an array of objects if more than once. This complicates the handling of the response, as we now have to determine whether the element being returned is a single object or an array of objects. 

Given the definition of such elements, we already expect the number of occurrences to be greater than 1. I hence propose that strong-soap should _always return an array of objects_ for such elements, so that response handlers can be simplified.

Desired behaviour can be inferred from vpulim/node-soap#1100

### PR DESCRIPTION
**Pull request by LoneRifle**
If the schema specifies an element having more than one occurrence,
honor this when JSONifying the response by ensuring that the
corresponding JSON property is always an array

- xmlToJson: on closing of tag, inspect its corresponding descriptor.
  if `descriptor.isMany`, enforce the property to be an array
- rework affected tests to account for this change

Fixes #268

### CODE REVIEW

**Comment by LoneRifle** [comment]
I've tried to account for the decrease in coverage, but coveralls is faulting me for a code path that is irrelevant to this PR

**Comment by LoneRifle** [comment]
Anything we can do to have this merged?

File: src/parser/xmlHandler.js [hunk 1]
```diff
@@ -648,7 +648,14 @@ class XMLHandler {
...
-        if (typeof top.object === 'object' && elementName in top.object) {
+        if (current.descriptor && current.descriptor.isMany) {
+          // Schema enforces array
+          if (!(elementName in top.object)) {
+            top.object[elementName] = [];
+          }
+          let val = top.object[elementName];
+          val.push(current.object);
+        } else if (typeof top.object === 'object' && elementName in top.object) {
           // The element exist already, let's create an array
```
Comment (deepakrkris) [inline src/parser/xmlHandler.js]: The block to check for isMany condition could be handled within the existing conditions isn't it ?

https://github.com/strongloop/strong-soap/blob/c40d08f2787aec03a7b6103f4d72e4bced2c410f/src/parser/xmlHandler.js#L651-L657

The reason I am asking is, as of now there are only two simple conditions in this block:
1. If the current element being parsed is already added to the wrapping element i.e., the top most in the stack.
        - this is to handle repetitive occurrences, sequences, etc of the current element
2. The current element should be added for the first time to its wrapping element
        - to link the current element to the wrapping element

You change seems to add an alternative path , just to check a value in the currently parsed element.

File: test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/common.xsd [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+	<xs:complexType name="Dummy">
+		<xs:simpleContent>
+			<xs:extension base="xs:string">
+				<xs:attribute name="language" type="xs:language" use="optional"/>
+			</xs:extension>
+		</xs:simpleContent>
+	</xs:complexType>
+	<xs:complexType name="DummyList">
+		<xs:sequence>
+			<xs:element name="DummyElement" type="tns:Dummy"/>
```
Comment (deepakrkris) [inline test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/common.xsd]: Why should a list with maximum length 1 considered an array ?

File: test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/response.xml [hunk 3]
```diff
@@ -0,0 +1,20 @@
+<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://www.Dummy.com" xmlns:n="http://www.Dummy.com/Name/Types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
+    <soap:Header></soap:Header>
+    <soap:Body>
+       <n:DummyResponse>
+           <n:DummyResult>
+               <c:DummyList xmlns:c="http://www.Dummy.com/Common/Types">
+                   <c:DummyElement>
```
Comment (deepakrkris) [inline test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/response.xml]: is this already handled , i.e, returning an array even for an element with maxoccurs 1, if multiple occurrences are found ?

Comment (deepakrkris) [reply test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/response.xml]: are we adding this test case for regression or is this test for the new proposed feature

Comment (LoneRifle) [reply test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/response.xml]: This is a test case for regression. The package as published already exhibits this behaviour.

File: test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/common.xsd (hunk 2 above)
Comment (LoneRifle) [reply test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/common.xsd]: For the reasons described in the issue that this PR seeks to resolve. See that issue for further explanation.

File: src/parser/xmlHandler.js (hunk 1 above)
Comment (LoneRifle) [reply src/parser/xmlHandler.js]: > 2. The current element should be added for the first time to its wrapping element
>    - to link the current element to the wrapping element

The flaw in this point is that if the schema specifies that the client should expect possibly more than one (but also possibly one) element, the current element does not get wrapped in an array. I can surely make the logic change within existing paths if that is desired, but I hesitate as I am unsure if I want it to be so intertwined and hence risk the code being less easy to reason about.

See accompanying issue for further explanation as to why maxOccurs > 1 should be handled differently, even when the actual number of elements returned is 1.

File: test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/common.xsd (hunk 2 above)
Comment (LoneRifle) [reply test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/common.xsd]: Because it is a list. See issue for further discussion on this.

**Comment by LoneRifle** [comment]
> @LoneRifle , we need some justification (with some code samples of existing clients) of why the array vs object checks are tedious and why that should be handled in the parser.

As a user of this library, I expect the shape of the object being returned to be consistent. I do not wish to write code that does:
```js
const data = await soapClient.GetFoo()
const result = {
  ...data,
  nestedField: Array.isArray(data.nestedField) ? data.nestedField : [data.nestedField],
}
```
or perhaps the somewhat more elegant:

```js
const data = await soapClient.GetFoo()
const result = {
  ...data,
  nestedField: [].concat(data.nestedField),
}
```

I just want to do:
```js
const result = await soapClient.GetFoo()
```
and move on, as I want to spend less time building handling logic and more time building actual business logic. This also influences how readable this is, and how much mental overhead users incur when dealing with responses returned by strong-loop SOAP clients

File: test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/common.xsd (hunk 2 above)
Comment (LoneRifle) [reply test/request-response-samples/Dummy__should_return_array_despite_maxOccurs_1/common.xsd]: This is existing behaviour found in strong-soap. Altering behaviour to honour maxOccurs=1 is outside the scope of this PR; doing so may actually break existing clients that rely on the dishonouring of maxOccurs=1.

File: src/parser/xmlHandler.js (hunk 1 above)
Comment (LoneRifle) [reply src/parser/xmlHandler.js]: That's a fair comment - I've made the change as proposed, though I feel that it might make the resulting code slightly more difficult to reason about

**Comment by raymondfeng** [comment]
@LoneRifle I think it's a breaking change. Maybe we should release it as a new major version?

**Comment by LoneRifle** [comment]
> @LoneRifle I think it's a breaking change. Maybe we should release it as a new major version?

That's fine by me. Thanks for both for vetting and accepting the PR!

**Comment by avindra** [comment]
Nice work @LoneRifle . I noticed this inconsistency too, and assumed the problem with the soap server...

I ended up patching in a fix through the ES6 `Proxy`, will test by removing my workaround and see if this satisfies the handling. I wonder how many of the users have some kind of `Array.isArray(x) ? x : [x]` logic in their apps :smile:
